=== esa/cstsapi-j/src/main/resources/SICFSchemaV2.2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by  (Telespazio Germany GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="MDSicf">
		<xs:annotation>
			<xs:documentation>root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ServiceInstances"/>
				<xs:element ref="ParameterDefinitions" minOccurs="0"/>
				<xs:element ref="enumDefinitions" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="TailoringVersion" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:key name="EnumKey">
			<xs:selector xpath="enumDefinitions/EnumType"/>
			<xs:field xpath="Reference"/>
		</xs:key>
		<xs:keyref name="EnumKeyRef" refer="EnumKey">
			<xs:selector xpath=".//ParameterDefinitions/Parameter/EnumReference"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:element name="enumDefinitions">
		<xs:annotation>
			<xs:documentation>enumerative definitions</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="EnumType" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Reference" type="xs:string"/>
							<xs:element name="Literals">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Literal" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="stringValue" type="xs:string" use="required"/>
												<xs:attribute name="intValue" type="xs:int" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="enumReferenceUnique">
			<xs:selector xpath="EnumType"/>
			<xs:field xpath="Reference"/>
		</xs:unique>
	</xs:element>
	<xs:element name="ParameterDefinitions">
		<xs:annotation>
			<xs:documentation>parameters definitions</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Parameter" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="paramOrEventId" type="xs:string"/>
							<xs:element name="FunctionalResourceType" type="xs:string"/>
							<xs:element name="FunctionalResourceInstance" type="xs:int"/>
							<xs:element name="Description" type="xs:string"/>
							<xs:element name="UnitOfMeasure" type="xs:string" minOccurs="0"/>
							<xs:element ref="ParameterType"/>
							<xs:element name="EnumReference" type="xs:string" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="OID" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="ParamNameUnique">
			<xs:selector xpath="Parameter"/>
			<xs:field xpath="@name"/>
			<xs:field xpath="@OID"/>
		</xs:unique>
	</xs:element>
	<xs:element name="ServiceInstances">
		<xs:annotation>
			<xs:documentation>service instances definitions</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ServiceInstance" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="initiatorIdentifier" type="xs:string"/>
							<xs:element name="responderIdentifier" type="xs:string"/>
							<xs:element name="ResponderPortId" type="xs:string"/>
							<xs:element name="UpdateCycleTime" type="xs:int"/>
							<xs:element name="SIParameterList" type="SIParameterListType">
								<xs:unique name="parameterNameParameterIdNameUnique">
									<xs:selector xpath="ParamEventName"/>
									<xs:field xpath="@name"/>
								</xs:unique>
								<xs:unique name="ListNameUnique">
									<xs:selector xpath="./ListName"/>
									<xs:field xpath="@name"/>
								</xs:unique>
								<xs:unique name="listParameterNameUnique">
									<xs:selector xpath="ListName/Parameter"/>
									<xs:field xpath="@name"/>
								</xs:unique>
								<xs:unique name="FunctionalResourceTypeUnique">
									<xs:selector xpath="./FunctionalResourceType"/>
									<xs:field xpath="."/>
								</xs:unique>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="SIID" type="xs:string" use="required"/>
						<xs:attribute name="stationOID" type="xs:string" use="required"/>
						<xs:attribute name="spacecraftOID" type="xs:string" use="required"/>
						<xs:attribute name="serviceOID" type="xs:string" use="required"/>
						<xs:attribute name="instance" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="SIIDUnique">
			<xs:selector xpath="ServiceInstance"/>
			<xs:field xpath="@SIID"/>
		</xs:unique>
	</xs:element>
	<xs:element name="ParameterType">
		<xs:annotation>
			<xs:documentation>parameter types</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="String"/>
				<xs:enumeration value="Integer"/>
				<xs:enumeration value="Double"/>
				<xs:enumeration value="Enumerative"/>
				<xs:enumeration value="Boolean"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="SIParameterListType">
		<xs:annotation>
			<xs:documentation>list of requests that MD client can ask to the MD provider</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ParamEventName" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="parameterOrEventId" type="xs:string" use="required"/>
					<xs:attribute name="functionalResourceType" type="xs:string" use="required"/>
					<xs:attribute name="functionalResourceInstance" type="xs:int" use="required"/>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="OID" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="FunctionalResourceName" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="functionalResourceType" type="xs:string" use="required"/>
					<xs:attribute name="functionalResourceInstance" type="xs:integer" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="ListName" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="parameterOrEventId" type="xs:string" use="required"/>
								<xs:attribute name="functionalResourceType" type="xs:string" use="required"/>
								<xs:attribute name="functionalResourceInstance" type="xs:int" use="required"/>
								<xs:attribute name="name" type="xs:string"/>
								<xs:attribute name="OID" type="xs:string"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="FunctionalResourceType" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ParameterEventLabel" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="parameterOrEventId" type="xs:string" use="required"/>
					<xs:attribute name="functionalResourceType" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== esa/cstsapi-j/src/test/resources/sicf_test_configurations.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<MDSicf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" TailoringVersion="V2.2" xsi:noNamespaceSchemaLocation="SICFSchemaV2.2.xsd">
    <ServiceInstances>
        <ServiceInstance SIID="spacecraft=gaia.facility=r68.service=md.instance=3" stationOID="1.5.1.2.1.2.1" spacecraftOID="1.3.112.4.7.0" serviceOID="1.3.112.4.4.1.2" instance="3">
            <initiatorIdentifier>CSTS_USER</initiatorIdentifier>
            <responderIdentifier>LMS</responderIdentifier>
            <ResponderPortId>CSTS_PT3</ResponderPortId>
            <UpdateCycleTime>5</UpdateCycleTime>
            <SIParameterList>
                <ListName>
                    <Parameter parameterOrEventId="/1" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680001" OID="1.3.112.4.4.2.1.1000.1.1.1" />
                    <Parameter parameterOrEventId="/2" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680002" OID="1.3.112.4.4.2.1.1000.1.2.1" />
                    <Parameter parameterOrEventId="/3" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680003" OID="1.3.112.4.4.2.1.1000.1.3.1" />
                    <Parameter parameterOrEventId="/4" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680004" OID="1.3.112.4.4.2.1.1000.1.4.1" />
                    <Parameter parameterOrEventId="/7" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680005" OID="1.3.112.4.4.2.1.1000.1.7.1" />
                    <Parameter parameterOrEventId="/8" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680006" OID="1.3.112.4.4.2.1.1000.1.8.1" />
                    <Parameter parameterOrEventId="/9" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680007" OID="1.3.112.4.4.2.1.1000.1.9.1" />
                    <Parameter parameterOrEventId="/10" functionalResourceType="/COR/TST1" functionalResourceInstance="1" name="R680008" OID="1.3.112.4.4.2.1.1000.1.10.1" />
                </ListName>
            </SIParameterList>
        </ServiceInstance>
    </ServiceInstances>
    <ParameterDefinitions>
        <Parameter name="R680001" OID="1.3.112.4.4.2.1.1000.1.1.1">
            <paramOrEventId>/1</paramOrEventId>
            <FunctionalResourceType>/COR/TST1</FunctionalResourceType>
            <FunctionalResourceInstance>1</FunctionalResourceInstance>
            <Description>Boolean Value</Description>
            <ParameterType>Boolean</ParameterType>
        </Parameter>
        <Parameter name="R680003" OID="1.3.112.4.4.2.1.1000.1.3.1">
            <paramOrEventId>/2</paramOrEventId>
            <FunctionalResourceType>/SYS/SUBS/OTHER</FunctionalResourceType>
            <FunctionalResourceInstance>0</FunctionalResourceInstance>
            <Description>Float Value</Description>
            <ParameterType>Double</ParameterType>
        </Parameter>
        <Parameter name="R680002" OID="1.3.112.4.4.2.1.1000.1.2.1">
            <paramOrEventId>/3</paramOrEventId>
            <FunctionalResourceType>/SYS/SUBS/OTHER</FunctionalResourceType>
            <FunctionalResourceInstance>2</FunctionalResourceInstance>
            <Description>Integer Value</Description>
            <ParameterType>Integer</ParameterType>
        </Parameter>
        <Parameter name="R680003" OID="1.3.112.4.4.2.1.1000.1.3.1">
            <paramOrEventId>/4</paramOrEventId>
            <FunctionalResourceType>/SYS/SUBS6/OTHER5/OTHER_OTHER</FunctionalResourceType>
            <FunctionalResourceInstance>42</FunctionalResourceInstance>
            <Description>Float Value</Description>
            <ParameterType>Double</ParameterType>
        </Parameter>
    </ParameterDefinitions>
    <enumDefinitions>
        <EnumType>
            <Reference>ESA_RESOURCE_STATE</Reference>
            <Literals>
                <Literal stringValue="UNKNOWN" intValue="0" />
                <Literal stringValue="KAPUT" intValue="1" />
                <Literal stringValue="FREE" intValue="2" />
                <Literal stringValue="START_REQ" intValue="3" />
                <Literal stringValue="ACTIVE" intValue="4" />
                <Literal stringValue="STOP_REQ" intValue="5" />
                <Literal stringValue="ABORT_REQ" intValue="6" />
            </Literals>
        </EnumType>
    </enumDefinitions>
</MDSicf>
