=== esa/cstsapi-j/src/main/java/esa/egos/proxy/xml/schema/ProviderConfig1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="provider_config" type="providerConfig"/>

  <xs:complexType name="providerConfig">
    <xs:sequence>
      <xs:element name="service_types" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="service_type" type="configServiceType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="remote_peers">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="remote_peer" type="remotePeer" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="local_logical_ports">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="logical_port" type="localLogicalPort" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="portlist" type="portList"/>
    </xs:sequence>
    <xs:attribute name="proxy_role" type="proxyRoleEnum" use="required"/>
    <xs:attribute name="local_id" type="xs:string" use="required"/>
    <xs:attribute name="local_password" type="xs:string" use="required"/>
    <xs:attribute name="startup_timer" type="xs:int" use="required"/>
    <xs:attribute name="non_useheartbeat" type="xs:boolean" use="required"/>
    <xs:attribute name="authentication_delay" type="xs:int" use="required"/>
    <xs:attribute name="transmit_queue_size" type="xs:int" use="required"/>
    <xs:attribute name="cs_address" type="xs:string" use="required"/>
    <xs:attribute name="default_reporting_address" type="xs:string" use="required"/>
    <xs:attribute name="use_nagel" type="xs:boolean" use="required"/>
    <xs:attribute name="min_deadfactor" type="xs:int" use="required"/>
    <xs:attribute name="max_deadfactor" type="xs:int" use="required"/>
    <xs:attribute name="min_heartbeat" type="xs:int" use="required"/>
    <xs:attribute name="max_heartbeat" type="xs:int" use="required"/>
    <xs:attribute name="transfer_type" type="transferType" use="required"/>
  </xs:complexType>

  <xs:complexType name="configServiceType">
    <xs:sequence>
      <xs:element name="srv_versions">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="srv_version" type="xs:int" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="srv_id" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="remotePeer">
    <xs:sequence/>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="authentication_mode" type="authenticationMode" use="required"/>
    <xs:attribute name="password" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="localLogicalPort">
    <xs:sequence>
      <xs:element name="port_data" type="portData" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="port_name" type="xs:string" use="required"/>
    <xs:attribute name="tcp_xmit_buffer_size" type="xs:int" use="required"/>
    <xs:attribute name="tcp_recv_buffer_size" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="portData">
    <xs:sequence/>
    <xs:attribute name="hostname" type="xs:string"/>
    <xs:attribute name="ip_address" type="xs:string"/>
    <xs:attribute name="port_number" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="portList">
    <xs:sequence>
      <xs:element name="port_mapping" type="portMapping" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="default" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="portMapping">
    <xs:sequence/>
    <xs:attribute name="responder_port_id" type="xs:string" use="required"/>
    <xs:attribute name="protocol_id" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:simpleType name="proxyRoleEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="INITIATOR"/>
      <xs:enumeration value="RESPONDER"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="authenticationMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE"/>
      <xs:enumeration value="BIND_ONLY"/>
      <xs:enumeration value="ALL"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="transferType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TIMELY"/>
      <xs:enumeration value="COMPLETE"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== esa/cstsapi-j/src/test/resources/ProviderConfig1.xml
<?xml version="1.0" encoding="UTF-8"?>
<provider_config oid_config_file="src/test/resources/OidConfig.xml" authentication_delay="180" local_id="CSTS-PROVIDER"
	local_password="000102030405060708090a0b0c0d0e0f" max_deadfactor="100"
	max_heartbeat="600" min_deadfactor="2" min_heartbeat="0"
	non_useheartbeat="true" proxy_role="RESPONDER" startup_timer="180"
	transmit_queue_size="10" use_nagel="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProviderConfig1.xsd" cs_address="5500"
	default_reporting_address="5510" transfer_type="TIMELY">
	<service_types>
	<!-- 
		<service_type srv_id="DUMMY">
			<srv_versions>
				<srv_version sfw="1">1</srv_version>
				<srv_version sfw="2">2</srv_version>
			</srv_versions>
		</service_type>
		<service_type srv_id="MONITORING">
			<srv_versions>
				<srv_version sfw="1">1</srv_version>
				<srv_version sfw="2">2</srv_version>
			</srv_versions>
		</service_type>
 -->
		<!-- Monitored Data Service -->
		<service_type srv_id="[1, 3, 112, 4, 4, 1, 2]">
			<srv_versions>
				<srv_version sfw="1">1</srv_version>
				<srv_version sfw="2">2</srv_version>
			</srv_versions>
		</service_type>

		<!-- Return CFDP PDU Service -->
		<service_type srv_id="[1, 3, 112, 4, 4, 1, 4]">
			<srv_versions>
				<srv_version sfw="1">1</srv_version>
				<srv_version sfw="2">2</srv_version>
			</srv_versions>
		</service_type>

	</service_types>
	<remote_peers>
		<remote_peer authentication_mode="NONE"
			password="ffdf01449809e4e5e677818892" id="CSTS-USER"></remote_peer>
	</remote_peers>
	<local_logical_ports>
	
		<logical_port tcp_recv_buffer_size="4096" port_name="CSTS_PT1"
			tcp_xmit_buffer_size="4096">
			<port_data port_number="5018" ip_address="*" />
		</logical_port>

		<logical_port tcp_recv_buffer_size="4096" port_name="CSTS_PT2"
			tcp_xmit_buffer_size="4096">
			<port_data port_number="5019" ip_address="*" />
		</logical_port>		
		
	</local_logical_ports>
	<portlist default="ISP1"></portlist>
</provider_config>
